[package]
name = "ttf-explorer"
version = "0.1.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
name = "ttfexplorer"
crate-type = ["staticlib"]

[dependencies]
tinyvec = "0.3.3"

[profile.release]
lto = true
